project_name: aqua
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/aqua
    binary: aqua
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
release:
  draft: true # we update release note manually before releasing
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    signature: '${artifact}.sig'
    certificate: '${artifact}.pem'
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
